# Site settings
title:Alogrithm Hub
email: w2442658418@163.com
url: https://example.github.io
description: "Welcome to Algorithm Hub , where everyone—from budding coders to seasoned developers—can explore, learn, and share algorithms. This vibrant platform  is designed to be a treasure trove of algorithmic knowledge, where you can discover practical resources , engage with fellow learners , and contribute to a growing community of enthusiasts ."

# Color settings (hex-codes without the leading hash-tag)
color:
  primary-dark: '#000000'
  links: '#219ab3'

# Footer settings
footer: Ezra-Wan

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: https://twitter.com/SBootstrap
  - title: facebook
    url:
  - title: stack-overflow
    url: http://stackoverflow.com/questions/tagged/jekyll
  - title: bitbucket
    url: http://bitbucket.org/jekyll
  - title: github
    url: https://github.com/IronSummitMedia/startbootstrap

# Build settings
markdown: kramdown
permalink: pretty
